### ISSUE TITLE
[FE] 회원가입, 로그인 화면 완성

### ISSUE THREAD

**Issue by lucyya99** [kookmin-sw/capstone-2023-08#104]
## 회원가입~로그인 남은 To-do
- [x] 카메라 실루엣 포토샵으로 제작
- [x] 회원가입 시 id 중복체크
- [x] 회원가입 시 id, pw 특수문자 제외 (ex. +, = 못들어가도록 설정)
- [x] 회원가입 시 닉네임 길이 제한 (10자이내)
- [x] ~카운트 다운 10 셀 때 처음부터 원이 다 채워지도록 변경~ 너무 디테일한 부분인 것 같아서 상태관리 등 완료 후에 다시 수정할게요 😥
- [x] 회원가입 overflow (login 방식으로 해결)
- [x] login textfield 변경 및 사용성 높이는 작업, 회원가입 버튼 변경
- [x] login textfield id, pw 둘 중 하나라도 null이면 버튼 비활성화
- [x] 회원가입 실패처리
- [x] #116

**Comment by lucyya99** [comment]
![Uploading Screenshot_20230506_005607.jpg…]()

**Comment by dh5473** [comment]
@lucyya99 
제 로컬에서는 GPU가 없어서 테스트 못합니다.
아직 jwt 반영을 안해서요, 나중에 시간 맞춰서 제가 AWS 서버 켜드리겠습니다.

**Comment by lucyya99** [comment]
넵 감사합니다!

**Comment by wynter122** [comment]
> "Duplicate entry 'admin1' for key 'accounts_user.user_name'"라고 뜨는데 혹시 user_name에도 unique로 설정되어있는지 확인부탁드립니다..! (user_name을 ADMIN1으로 보내도 같은 문제가 발생하네요 - "Duplicate entry 'ADMIN1' for key 'accounts_use r.user_name'")
-> 네 파악하신대로 회원정보는 패스워드 말고는 모두 unique 가 설정되어있습니다. 대소문자 구분을 하지않는 것 같아요. 유의해서 테스트하시면 됩니다.

> 테스트를 너무 많이해서 DB가 좀 더러워졌을 것 같아서 다음주 중으로 한번 정리해야할 것 같아요.. (이건 굳이 필요없으면 안해도 됩니다)
-> DB 는 안해도 될 것 같은데, 다만 s3에 너무 업로드 요청을 많이 보내면 비용이 청구될 수 있으니 s3 와의 통신을 불필요하게만 많이 하지 않으시면 될 것 같습니다.

**Comment by lucyya99** [comment]
회원가입 시 validation 유저의 입력에 따라 실시간으로 받도록 변경 (응답받는 시간이 있어서 약간 딜레이가 생기는데, 다른거 입력하는 시간도 있어서 이 정도는 괜찮을 것 같아요..!)
![Animation3](https://user-images.githubusercontent.com/80736490/236784080-e447ba9a-13d2-46ff-826c-beca72ab55c2.gif)

**Comment by lucyya99** [comment]
검정색 / 노란색으로 만들어서 노란색으로 다시 넣었고, 색상은 내일 괜찮은지 같이 확인해보고 PR 넣을때 반영해서 넣으면 될것같아요 나머지는 해결되어서 이슈 닫습니다!
