### ISSUE TITLE
[BE] 토큰 도입에 따른 API 받는 방식 변경 이슈

### ISSUE THREAD

**Issue by wynter122** [kookmin-sw/capstone-2023-08#108]
#95 에서 토큰을 도입하면서 나머지 API 에서도 permissions 를 추가하고, 토큰 기반으로 user 정보를 식별하도록 변경하는 이슈입니다.

**Comment by wynter122** [comment]
# View 별 permission 구성 계획
제가 구현한 View마다 적절한 permission 을 지정했습니다.
@lucyya99 @grapefruit224 은 보고 적절하지 않은 부분이 있으면 피드백 주세요.

### accounts

1. SignUp view : Allow Any
    
    → 회원가입 성공시 토큰 반환
    
2. SignIn view : Allow Any
    
    → 로그인 성공시 토큰 반환
    

### musinsa_list

1. RecieveCrawlingResultView : Allow Any
    
    → 크롤링 정보 받아서 처리하는건데 굳이 authentication X
    
2. ShowClothListView : IsAuthenticated
    
    → 로그인이 되어야 무신사 옷 입어보기 버튼 누를 수 있음
    
3. ShowDetailView : IsAuthenticated
    
    → 로그인이 되어야 무신사 옷 세부페이지 넘어갈 수 있음
    
4. DipsView : IsAuthenticated
    
    → 로그인이 되어야 찜하기 가능
    

### s3_access

1. CreatePresingedUrl : AllowAny
    
    → 회원가입 이전에 presigned url 을 반환하여 s3에 업로드해야하기 때문에 allow any.
    
    다만, 회원정보 수정에도 같은 api 를 사용하기 때문에 IsAuthenticated 가 적절해보이기는 하나, 그렇게 하면 회원가입 로직을 변경해야하므로 간단하게 allow any 로 지정

**Comment by wynter122** [comment]
musinsa_list app 의 DipsView 의 경우 토큰기반으로 백단에서 user_정보를 식별해야합니다.

**Comment by lucyya99** [comment]
회원가입 빼고는 전부 다 적절한 것 같아요..! 회원가입 이후에 바로 토큰을 받아 로그인하도록 설정할까요?

**Comment by wynter122** [comment]
회원가입 결과에서 토큰을 발급하는것 말씀하시는거 맞을까요

대부분의 레퍼런스에서 회원가입 이후에도 토큰을 발급하더라구요. 
예지님말씀대로 회원가입 이후에 바로 로그인을 해도 될 것 같지만, 일반적으로는 로그인을 다시 시도하니 토큰 발급을 빼는게 나을 것 같긴 해요
