### ISSUE TITLE
[BE] DL API request

### ISSUE THREAD

**Issue by dh5473** [kookmin-sw/capstone-2023-08#111]
@lucyya99 
해당 url로 request 보내주시면 됩니다.

![image](https://user-images.githubusercontent.com/94889715/235685421-40c5835a-cafb-4a9f-91df-6cf1e988cb50.png)

각 API의 보내주어야하는 request key는 아래와 같습니다.
human_img_path
cloth_img_path
human_img_path, cloth_img_path

**Comment by dh5473** [comment]
예시입니다!
![image](https://user-images.githubusercontent.com/94889715/235686552-a695826b-53f5-447d-b7fd-353a56c39a8d.png)

**Comment by lucyya99** [comment]
ip도 그렇고 혹시 로컬에서 실행해야하나요..? 요청이 성공적으로 갔는지 테스트할 방법이 있을까요??

**Comment by wynter122** [comment]
완료되어 이슈닫습니다
