### ISSUE TITLE
[TEST] "피팅하기" (Inference) api 프론트 - 서버 테스트

### ISSUE THREAD

**Issue by wynter122** [kookmin-sw/capstone-2023-08#124]
프론트에서 "피팅하기" 부분에서 api 를 요청했을 때 동작테스트를 진행하는 이슈입니다.
(Inference API)

주로 테스트 해야 할 것들
1. api 에서 정의한 input, output 형식의 이상 유무
2. request ~ response 까지 총 소요시간 -> 결과에 따라서 로딩화면 기능 픽스 바로 진행

### 테스트 진행 전에 수행했으면 하는 것
지금 @dh5473 님 코드가 dl-setting 에만 존재하고, Backend 로 PR 이 안와서 merge 가 안됐는데요,
인스턴스 서버에서는 최대한 Backend 브랜치만 사용하는게 관리가 편해서, 테스트 이전에 PR 하고 코드리뷰 하면 좋겠습니다.
PR 이후에 제가 브랜치 최신화 시켜둘게요 (혹시 conflict 날 것 같아서요!)

그리고 GPU 서버는 과금이 많이 되니 최대한 아껴서 사용해주세요..!

결과는 해당 이슈에 공유해주시면 감사하겠습니다.

**Comment by dh5473** [comment]
내일 PR 올릴게요~

**Comment by wynter122** [comment]
## DL PR 반영 완료

gpu-server 인스턴스에 #127 PR 반영 완료했고 마이그레이션까지 마쳤습니다.
서버 올릴때는 접속하자마자 `bash *.sh` 실행하시면 됩니다.

<img width="1552" alt="스크린샷 2023-05-10 오후 3 12 23" src="https://github.com/kookmin-sw/capstone-2023-08/assets/72314987/20d5b176-9926-40f8-92f1-2f3e3583516d">

**Comment by wynter122** [comment]
Api는 잘 작동하고 넉넉잡아 15초 이내정도 소요된다고 보면 될것같습니다.

파일 변환에서 이슈가 발생해서 수정사항은 다음과같이 파악됩니다.

- 백단에서 파일 response -> s3 저장 후 s3 url 을 response로 전달 (@dh5473)

- 프론트에서는 response 받은 후, get presigned url api로 해당 파일 접근 권한 얻기 -> 얻은 url로 파일 받아서 띄우기
(@lucyya99)

- s3에 저장된 리소스에 get 접근 권한부여하도록 get presigned url api 수정
(put obj, get obj 를 파라미터로 받도록 수정할거같아요) (@wynter122)

### 결과사진 관련하여
s3에서 받은 사진은 png 형식이기 때문에
무신사 옷 화면, 찜목록 화면처럼 url을 넣어서 단순히 보여주는게 안됩니다. (jpg만 가능)

html상에서는 png 형식의 s3 리소스를 클릭한다면 로컬로 다운을 받게 되는데 플러터에서는 어떻게 처리가 되는지 확인해서 알려주세요
(플러터 스토리지에 저장이 되는지, 사용자 갤러리에 저장이 되는지)

만약 바로 사용자 갤러리로 저장이 된다면 해당 구현 방식은 더 생각을 해봐야합니다. 갤러리 저장버튼을 누르기 전에 저장이 되기 때문입니다.

**Comment by lucyya99** [comment]
[레퍼런스](https://stackoverflow.com/questions/59616610/how-can-i-download-file-using-flutter-dio)입니다 ㅠㅠ

아까 Image.network()로 받았던게 file:///로 나와서 혹시 파일 자체를 다운받아야하나 해서 temporary path 받아와서 저장했더니 되네요

```
Directory tempDir = await getTemporaryDirectory();
String tempPath = tempDir.path;
String path = '$tempPath/${id}_result.png';
File file = File(path);
var raf = file.openSync(mode: FileMode.write);
raf.writeFromSync(response.data);
await raf.close();
```

다들 고생많으셨어요..!

**Comment by wynter122** [comment]
테스트 완료되어 이슈 닫습니다
디자이너분한테는 10~15초 정도로생각하고 로딩화면 구상해달라고 전달하겠습니다.

이후 예지님은 #92 진행한뒤에, 완료되면 로그인부터 한번에 잘되는지 확인해보도록 하죠!
