### ISSUE TITLE
[BE] 기타 API 추가

### ISSUE THREAD

**Issue by wynter122** [kookmin-sw/capstone-2023-08#134]
현재 UI 상에는 표시되어있지만, API 는 정의되지 않은 기능들은 다음과 같습니다.

- 닉네임 수정
- 비밀번호 수정
- 로그아웃

추가적으로 제가 파악하지 못한 API 가 있으면 확인해보시고 코멘트 달아주세요

(참고로 공지사항은 그냥 .. 빼는게 나을 것 같아서 안만들었습니다. 저희 GItpage 연결하시는거 구현해놓으셔서 필요없을 것 같아요)

@lucyya99 @grapefruit224

**Comment by lucyya99** [comment]
공지사항은 저도 없앴습니다..! 그냥 깃헙 페이지 보여주는것까지 해도 화면이 꽉차서 괜찮을것같아요

로그인에서 도와드릴까요..?하고 아이디찾기 / 비밀번호 찾기같은거 넣으려고 했는데 해야할까요...? 😥

**Comment by wynter122** [comment]
음... 기능상으로 어렵지는 않지만
저희가 회원가입 정보를 너무 간단하게 받아서 id를 찾을래야 찾을 수 없지 않을까요...?
이메일이나 번호를 받은게 아니라 인증이 안되니까...
그냥 하지 말져!

**Comment by wynter122** [comment]
프론트단과 테스트 완료
