### ISSUE TITLE
[FE] 남은 task 정리

### ISSUE THREAD

**Issue by lucyya99** [kookmin-sw/capstone-2023-08#140]
1번빼고는 계속 해왔던 것들이라 어렵지 않을 것 같아요! 
금요일 전까지 6번까지하고, 금요일에 마지막 테스트 진행하면 될 것 같습니다

- [x] Native Splash Screen, icon 넣기
- [x] 로그인, 회원가입 api 수정내역 확인 및 프론트에 반영
- [x] #92 피드백 반영
- [x] 위의 3가지 테스크 수행 후 소정님 코드와 머지
- [ ] #139 수행
- [ ] 소정님 코드와 머지된 것으로 결과 요청까지 테스트, 온보딩 페이지용 gif 만들어서 넣기

**Comment by lucyya99** [comment]
## 마지막 테스트 체크사항
1. 카메라 사진 -> medium, high 중 어떤 것으로 설정할지
2. 직접 사진 찍어서 테스트해봤을 때 결과가 잘 나오는지
3. 결과 페이지에서 사진이 너무 흐릿하게 나오진 않는지 (너무 흐릿하면 원래대로 크기 설정하도록 변경, 비는 부분은 로딩 페이지처럼 만들어서 채우는 방향도 생각해봤음)
4. 로딩 페이지 시간이 너무 늦진 않는지 (확인했지만, 이번 로딩 화면으로 충분한지만 다시 점검)
5. 결과 피드백 api 정상 요청 / 응답하는지
6. 전체적인 UI 디자인 맞게 되었는지 점검

**Comment by lucyya99** [comment]
### 테스트 결과
1. 주변에 아예 아무것도 없이 하얀색이어야 결과가 잘 나옴
2. 왜인지 모르게 request가 여러번 되거나 팝업창이 여러번 뜨는 문제
3. dialog -> pop시 이상하게 뜨는 문제 (이상하게 갤러리버튼 -> 피팅화면은 괜찮은데, 무신사 -> 피팅화면에서 이런 버그가 발생)

### 추후 수정
- [ ] 카메라 비율을 4:3으로 고정되게 변경 (결과 사진 비율 = 192 *256으로 3:4 비율)
- [ ] 후면 카메라의 사진이 왼쪽으로 90도 회전되어 저장되는 문제 => 오른쪽으로 90도 회전하는 것으로 수정 - 서버에 저장될 때 
- [ ] 왜인지 모르게 request가 여러번 뜨는 문제
- [ ] 왜인지 모르게 팝업창이 여러번 뜨는 문제
- [ ] dialog -> pop시 이상하게 뜨는 문제
- [ ] 로딩창 뒷부분 검정색이 없어지는 문제

**Comment by lucyya99** [comment]
머지되면 이 이슈는 닫겠습니다!

**Comment by wynter122** [comment]
이거 5/24까지 수정 모두 안될거같은데...
제 생각에는 안고가야할것들은 일단 우선순위를 뒤로 빼야할거같아요
예를들면 원인을 잘 모르겠는 버그...(2, 3번)

그리고, 4번같은경우는 저희가 후면카메라는 안쓰기로 처음부터 얘기를 한 번 했고, 데모때에도 쓰게될 시나리오가 딱히 없어서 수정에 힘쓰지 않아도 될거같아요.

6번은 혹시 Human parsing 이 다 되고 나서야 회원가입이 완료되나요?
그렇다면 로직이 이상한거같은데... 그냥 요청만 보내고 회원가입 완료 한뒤에
백에서는 따로 human parsing 을 진행해야하지 않을까요?

그리고 디자인 변경은... 이제는 손을 떼야하지않을까싶습니다...

**Comment by lucyya99** [comment]
디자인 변경은 없어요..! 첫번째랑 pr한거 때문에 말씀하신것같은데 pr한건 피그마에 있는거랑 비슷하게 변경한거고 기능적인것만 소정님이 수정해주심돼요 첫번째는 디자인 변경이 아니라 파라미터만 수정하는거에요..!

**Comment by wynter122** [comment]
아 저는 7번을 보고 말씀드린거라서... 일단알겠습니다!

6번은 어떻게 되는건가요? 현재 human parsing 끝날때까지 회원가입 완료가 딜레이되는게 맞나요?

**Comment by lucyya99** [comment]
@wynter122 
아하 원래대로 그냥 흰바탕 검은글씨로 하려구요 그런것같아요 갤러리 선택해서 s3 올리는건 시간이 적게 걸려서.. 그거 그냥 await 키워드 없애면 돼요!
