### ISSUE TITLE
[기말] 최종 시스템 구조도

### ISSUE THREAD

**Issue by wynter122** [kookmin-sw/capstone-2023-08#141]
#135 #136 에서 사용

**Comment by wynter122** [comment]
- 피팅 결과 페이지
- 피드백 받는 화면
- 갤러리에 저장하는 화면

이 세가지 프레임의 최종 화면이 필요합니다. Figma 에 만들어주시면 제가 png 따서 넣겠습니다.
업데이트해서 알려주세요.

<img width="347" alt="image" src="https://github.com/kookmin-sw/capstone-2023-08/assets/72314987/1d658d9e-186b-4cfd-828e-44fd3876be8a">

그리고, 결과 피드백 api -> 사진저장 순서가 맞나요??

@lucyya99 @grapefruit224

**Comment by lucyya99** [comment]
피그마 업데이트 하였습니다! 피그마 바탕으로 만드실 것 같아서 실제로 구현한거 캡처본이랑 피그마 화면 두개 다 만들어서 넣어두었어요 추가로 요청할거 있으면 알려주세요

이번주 회의록에 결과페이지 gif에도 있지만,
엄지다운 = 서버에 결과이미지 저장하도록 요청
엄지척 = [피팅결과가 마음에 드시나요? 처음으로 / 사진저장] -> 이렇게 한번 더 팝업이 뜨도록 만들었습니다

엄지척을 누르면 그냥 바로 사진저장할까도 생각해봤는데, 사용자가 선택하는게 나을 것 같아서 그냥 이렇게 만들었어요

**Comment by wynter122** [comment]
사진이 마음에 들지 않아도 저장은 할 수 있는 선택지는 줘야하지 않을까요??

"결과가 마음에 드시나요?" Bad, Good 결과 피드백
-> 의견 감사합니다. 주신 결과는 뭐 더 나은 서비스를 제공하는데에 사용됩니다.~ 뭐이런식으로 메세지를 포함해서 [메인 / 갤러리저장] 선택 팝업창을 띄워도 괜찮을 것 같아요.

**Comment by lucyya99** [comment]
<img src="https://github.com/kookmin-sw/capstone-2023-08/assets/80736490/db90c161-b392-47e9-a4fd-bf675c2e37b9" width=40%>
<img src="https://github.com/kookmin-sw/capstone-2023-08/assets/80736490/78db288f-079f-4c83-a2f5-ec00dff34114" width=40%>
이렇게 업데이트 해뒀습니다 이거 바탕으로 수정해둘게요

**Comment by wynter122** [comment]
[시스템 구조 수정.pdf](https://github.com/kookmin-sw/capstone-2023-08/files/11522696/default.pdf)

- human parsing + 옷 고르기 -> 결과 사진으로 수정
- 양옆으로 길게 만들기
