### ISSUE TITLE
GitPage 및 Readme 수정

### ISSUE THREAD

**Issue by wynter122** [kookmin-sw/capstone-2023-08#147]

**Comment by wynter122** [comment]
GitPage 및 Readme 수정사항

1. 소개동영상 수정 (GitPage, 리드미)
아래 링크로 바꿔주세요
<iframe width="560" height="315" src="https://www.youtube.com/embed/z_zzDvQsTQE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

2. 로고 수정 (GitPage)
새로 바뀐 로고로 수정해주세요.

3. 사용방법 추가 (리드미)
UI 넣어서 사용방법 작성해주세요.

4. 이메일 추가 (리드미) : kmucapstone08@gmail.com 로 링크걸어주세요
(걸기 어려우면 그냥 기재만)

**Comment by lucyya99** [comment]
![mainIcon](https://github.com/kookmin-sw/capstone-2023-08/assets/80736490/d305e4c5-d2ad-466d-a37e-663a45a2970d)
