### ISSUE TITLE
프론트 및 백엔드 구조 관련 순서 수정

### ISSUE THREAD

**Issue by dh5473** [kookmin-sw/capstone-2023-08#24]
이전에 프론트 구조로 main -> 옷 사진 선택 -> User 촬영 -> Output 순서로 논의했었는데, 구조를 약간 수정해야 할 것 같습니다. 옷 사진 선택 이전에 User 촬영을 먼저 해야할 것 같아요. DL 파트 중 Human Parsing 이라는 과정이 있는데 모델이 무거워서 1분 가량 소요됩니다. 따라서 이 부분을 앞에 배치하고, 사용자가 옷 사진을 선택하는 동안 백그라운드에서 돌리면 좋을 것 같습니다.

main -> User 촬영 -> 옷 사진 선택 -> Output

일단은 위와 같이 진행된다고 생각해주세요!
확인하셨으면 이모지 부탁드려요. 전부 체크되면 이슈 닫을게요.

![구조](https://user-images.githubusercontent.com/94889715/223949946-f93c4f8b-ba4b-49bd-985a-ec8bd98671e9.jpg)

**Comment by wynter122** [comment]
이슈는 프론트단에서 이 부분 해결하면서 닫아도 될거같아요
