### ISSUE TITLE
[중간평가] Github Pages 및 README.md 작성

### ISSUE THREAD

**Issue by wynter122** [kookmin-sw/capstone-2023-08#28]
**기한 : 4/3**

**Comment by lucyya99** [comment]
## Git Page 링크 바로 이동하기
[Capstone 08팀 Git Page Link](https://kookmin-sw.github.io/capstone-2023-08/)

## 테마 선정 기준
1. 데모페이지 운영, 깃헙에 코드 존재
2. 기본 언어가 중국어 아닌거
3. 어플을 설명하는 페이지가 메인
4. 그외에도 블로그글 (설명서 등등) 작성 가능

## 선정한 지킬 테마
Hydra - [Demo link](https://proud-alligator.cloudvent.net/), [Github](https://github.com/CloudCannon/hydra-jekyll-template)

- 장점 : _config.yaml 파일과 약간의 문구만 수정해주면 완성된 느낌의 페이지를 만들 수 있음

- 단점 : server, client로 구성되어있던 repository 메인에 잡다한 파일들이 많이 생김

단점은 다음과 같은 방법으로 해결 가능합니다.
1. Master 브랜치에 /docs 폴더 생성 후 코드 넣기
2. 다른 브랜치에 깃페이지 호스팅하도록 설정

저희가 기능별로 브랜치를 운영중이기때문에 브랜치를 생성해서 운영하는 2번 방식으로 진행하겠습니다!

**Comment by wynter122** [comment]
헉 완전 잘 꾸려졌네요...!!!
해당 이슈는 예지님이 주로 진행하시면 좋을 듯 하고,
추가적으로 wiki나 설명글을 써야하는게 필요하다면 모두 하나씩 맡아서 작성하면 좋을 듯 합니다!!

**Comment by lucyya99** [comment]
[Git page 지킬 테마 추가 및 index.html 약간 수정]에 사용법을 적어뒀습니다!
추가로, Git Page가 작동하는지 + 어디서 오류가 발생하는지 보려면 Actions 탭에 들어가면 됩니다.

**Comment by grapefruit224** [comment]
<img width="536" alt="스크린샷 2023-03-17 오후 5 05 52" src="https://user-images.githubusercontent.com/55117023/225847868-79bcd835-6d3b-4db4-b581-267dff124796.png">

**Comment by lucyya99** [comment]
<img src="https://user-images.githubusercontent.com/80736490/226527255-95100582-ed1b-49eb-a940-f5322efea23d.png" width=80%/>

<img src="https://user-images.githubusercontent.com/80736490/226527259-a7be8935-bee0-43e5-9f4f-c0424435978c.png" width=80%/>

<img src="https://user-images.githubusercontent.com/80736490/226527261-5e1e8a7f-f3a0-43f0-9b00-60d8d80868d8.png" width=80%/>
현재 이렇게 구성되었습니다!

## 앞으로 남은 일
1. favicon 및 logo 이미지 가로로 긴 버전, 정사각형 버전 (대충이라도 수정, Hydra라는 문구 대신 우리 어플 이름만 박히도록 하는게 목표!)
2. 요청한 이미지 올리기, 메인페이지 무료 이미지 찾아보기
3. 각자 프로필 작성
4. blog글 1개 작성 (페이지가 너무 비어보임)
5. 어플 이름으로 싹 고치기

**Comment by wynter122** [comment]
![IMG_9245](https://user-images.githubusercontent.com/72314987/226894718-572ca79c-a1b1-4180-bc72-66ce536dc1f5.jpg)

**Comment by dh5473** [comment]
![소개사진](https://user-images.githubusercontent.com/94889715/229057365-271fdb0e-8010-4623-a7e8-33e6ffeb6a41.jpg)

**Comment by lucyya99** [comment]
![image](https://user-images.githubusercontent.com/80736490/229059105-b118ccf4-6604-4889-9943-5302f879d146.png)

**Comment by lucyya99** [comment]
메인화면에 들어갈 나머지 이미지는 구했는데, 메인페이지 첫번째에 넣을 사진을 못 구해서 대충 작업해서 올린 예시 이미지입니다.
글과 함께 나오는 이미지는 보통 사진인데, 곰돌이가 들어가는게 좀 어색하고 유치한 느낌을 주는것 같아요.. 
괜찮은 이미지들은 2~3만원씩해서 조금 부담스럽고, 사진을 직접 촬영해서 넣는것도 좀 힘들 것 같아서 고민중입니다. 의견이나 좋은 사진 있으면 알려주세요 😥 그리고 일단 곰돌이 들어간 사진으로 PR 올려놓을게요!


<img src="https://user-images.githubusercontent.com/80736490/229305281-584a1bf7-b948-46dc-b7bf-a174c12c6d1f.png" width=30%/> <img src="https://user-images.githubusercontent.com/80736490/229305283-e8c1363d-02d4-4036-a347-915e4ccb3624.png" width=30%/>

<img src="https://user-images.githubusercontent.com/80736490/229305284-91866e79-fe02-44dd-af34-e6f462f01956.png" width=30%/> <img src="https://user-images.githubusercontent.com/80736490/229305285-d1ce1a76-e7e0-4814-9fcc-d9629dc61d34.png"
 width=30%/>

**Comment by wynter122** [comment]
저는 그냥 저희 로고만 들어가도 충분한것같아요!! 한가지 수정할건 "무신사에서 top 90 옷을 입어보세요" -> "무신사의 옷들을 입어보세요" 이렇게 바꿔야할것같아요!

**Comment by wynter122** [comment]
중간평가를 위한 Gitpage 및 Readme 작성되어 close 합니다
