### ISSUE TITLE
UI 업데이트 관련된 이슈

### ISSUE THREAD

**Issue by lucyya99** [kookmin-sw/capstone-2023-08#3]
본 이슈는 UI 구성을 트래킹하기 위한 목적입니다.

[Figma 링크](https://www.figma.com/file/vYoR1i1iTqB6RuS5F5GyH1/UI-Design?node-id=0%3A1&t=hGaJWoSO0GdjA3qZ-0)

# 첫번째 UI 디자인
## 진행상황
현재 완료된 것은 **[로그인, 회원가입, 마이페이지, 메인화면ver1, 메인화면ver2]**입니다.
이 중 설명이 필요한 것만 간단하게 이슈로 작성하겠습니다. 나머지는 Figma 주석을 참고해주세요. 
메인컬러가 정해지지 않아 회색을 위주로 작업해 칙칙해보일 수 있습니다.

**1. 메인화면 ver1.
사진 혹은 무신사 랭킹에서 옷을 고릅니다 -> 카메라를 가이드라인에 맞게 조정합니다 -> 가이드라인에 대략적으로 맞으면, 자동으로 촬영합니다 -> 가상 피팅된 사진을 보여줍니다**
![Screenshot 2023-01-19 180154](https://user-images.githubusercontent.com/80736490/213400620-9a4bd061-6a79-469f-b39d-64a8a3bf78d8.png) ![Screenshot 2023-01-19 180210](https://user-images.githubusercontent.com/80736490/213400628-8b2e5c38-2892-4a5a-8235-bc2a7b3f6616.png) ![Screenshot 2023-01-19 180226](https://user-images.githubusercontent.com/80736490/213400634-160d3363-4a26-4f28-ba62-d68c8b9afc67.png)
*자동으로 촬영하는 기능은 미팅때 없던 기능인데, 전신 촬영시 사용자가 버튼을 누를 수 없을 것 같아 임의로 넣어두었습니다.
**2. 메인화면 ver2.**
ROUNDS라는 안경피팅어플을 많이 참고했습니다.
![Screenshot 2023-01-19 180239](https://user-images.githubusercontent.com/80736490/213400716-761cfaaa-d961-487f-ba5e-00add48e76d9.png)
**기본적으로 카메라를 보여줍니다.** 카메라 화면 위에 [우상단, 하단, 하단바] 버튼을 위치했습니다.
우상단에는 '나'대신 모델을 피팅하도록 바꾸는 버튼, 하단에는 무신사 옷 추천을 넣었습니다.
하단바 가운데에 **갤러리 버튼에서 원하는 옷을 갤러리에서 찾아 피팅할 수 있고, 선택 후 "가이드라인에 대략적으로 맞으면, 가상 피팅된 사진을 보여줍니다"로 진행될 것 같습니다.**
카메라가 메인인 것 빼고는 메인화면 ver1처럼 사진을 넣어서 촬영하도록 바꿀 수 있습니다.
3. 마이페이지
![Screenshot 2023-01-19 180140](https://user-images.githubusercontent.com/80736490/213401488-1459b79f-1b68-4738-9ca1-38acf7e93213.png)
저희 어플에서 입어본 피팅사진 저장이 필요할 것 같아 LookBook 페이지를 만들었고, 추천시스템을 마이페이지 안에 넣었습니다. 마이페이지는 내일 중 수정할 예정입니다!
4. 로고와 메인문구
임의로 로고는 'Fit in, Fit me!', 메인문구는 '원하는 옷을 원하는 장소에서 입어보세요!'로 정하고 작업했습니다.
## 추가적으로 작업이 필요한 페이지
추천화면과 무신사 관련 쇼핑몰 랭킹 피팅 페이지를 작업할 예정입니다.
## 메인화면 ver1, ver2 중 선정
메인화면 ver1과 ver2 중에서 flow가 단순한 것은 ver1이지만, ver2는 집약적으로 정보를 모아두었습니다.
두 메인화면 중 선택이 필요할 것 같습니다!

**Comment by wynter122** [comment]
@lucyya99 @grapefruit224 
찜목록이랑 마이페이지 UI 작업이 필요합니다

**Comment by lucyya99** [comment]
마이페이지 UI 입니다. 
- 필요한 것
1. 프로필 사진
2. 이메일 or 휴대폰번호
3. 신체사진
4. 이름/닉네임
5. 고객센터, help (는 메뉴가 적어보여서 넣긴 했는데, 정말로 추가해야할지는 같이 생각해봐야할 것 같아요)

프로필 사진은 논의하지 않았던 부분인데, 그때 말씀드렸던 커뮤니티로의 확장성까지 고려하면 넣어야할 것 같아요.

![화면 캡처 2023-03-18 172105](https://user-images.githubusercontent.com/80736490/226094237-9646cff0-21ad-4247-817c-923db2cc16c7.png)

**Comment by wynter122** [comment]
마이페이지에서 사용자 프로필 사진은 우선... 안넣는게 좋을 것 같아요.

저희가 애초에 구현하고자 한 추천 시스템도 구현이 가능할지 미지수라 보류중인데 커뮤니티 기능도 시간이 충분치 않을 것 같아요.
또, 우선 로그인 및 회원가입 API에 맞춰 DB 모델을 구성해둔 상태인데 거기서 프로필 사진까지 추가 (s3 에도 추가가 필요해서요) 하는건 보류를 하는게 좋을 것 같아요.
시간이 정해진 상황에서 구현을 할지 안할지 결정되지 않는것에 가능성을 두는건 비효율적인 작업이 될 것 같습니다.
게다가, 프로필 사진까지 사용을 한다면 차라리 카카오 로그인 api를 사용하는게 오히려 좋은 방법일 수 있어요.

우선, 더 멀리 보기보다는 중간평가를 목표로 이미 개발된 api 에 맞게 정보를 불러오는 마이페이지로 구현하는게 좋을 것 같다는 생각입니다.

**Comment by lucyya99** [comment]
![화면 캡처 2023-03-21 215706](https://user-images.githubusercontent.com/80736490/226616598-3686d287-9e9b-471f-89ce-b3e1e3f4d65d.png)

1. 로그아웃 추가
2. 계정정보와 어플정보, 로그아웃간 간격을 위해 선 추가
3. 사용자가 실수로 수정하기 쉬운 것들은 설정아이콘이나 이동버튼을 눌러 다른 페이지로 이동해야 가능하게 설정
4. 회원정보 수정시 인증 x (마이페이지 -> 인증 -> 회원정보 수정 - X, 마이페이지 -> 회원정보 수정 - O)

**Comment by lucyya99** [comment]
1. 피팅페이지에 필요한 화면들
<img src="https://user-images.githubusercontent.com/80736490/226858925-cd26e5b9-6813-43f8-aa3f-5619abfc8626.gif" width=40%/>
- 로딩 -> 생성완료 -> 피팅결과페이지 -> 갤러리에 저장/이전화면으로 돌아가기

중간에 피팅 결과 페이지에 [갤러리에 저장/이전화면으로 돌아가기]를 통합할 단어와 버튼 위치를 구상중인데 잘안되네요ㅠ

2. 갤러리에서 불러오기
<img src="https://user-images.githubusercontent.com/80736490/226858937-032343db-f78c-4b05-b7c0-4324e8f106bd.gif" width=40%/>
- 이미지가 있는 경우 : 잘되는 사진 안내문구 -> 사진 선택 -> 경고창
- 이미지가 없는 경우 : 맨 마지막 화면
