### ISSUE TITLE
[중간평가] 시스템 구조도 작성

### ISSUE THREAD

**Issue by wynter122** [kookmin-sw/capstone-2023-08#36]
중간평가에서 7분내의 pdf 발표 자료를 만들어야합니다.
본 이슈에서는, 현재 개발된 기능들 + 개발하기로 논의된 기능 위주로 시스템 구조도를 그려 발표에서 사용하고
앞으로 있을 개발에서도 참고하도록 합니다.

**Comment by wynter122** [comment]
추상화는 별거 아니고 저기서 제가 User Id, User img 경로 등 post 를 날릴때 필요한 요소를 상세히 적어두었는데, 저런걸 간략하게 나타낼 수 있는정도면 좋을 것 같아요. 에를들면 회원가입할때에는 실제로 많은 요소들이 전달되지만 "User 정보" 라고만 표현해두었습니다.
모델 파트를 따로 구조로 만드는것도 괜찮은데, 모델 파트를 따로 그릴때도 모든 요소를 표현할 수 없어서 어떻게 간단하지만 정확하게 표현이 가능할지를 추상화라고 말씀드렸습니다.

**Comment by wynter122** [comment]
# 구현 완료된 UI 및 아이콘 반영

### 메인 시스템 구조도
![image](https://user-images.githubusercontent.com/72314987/226821431-893f3383-bb35-483a-8f68-10395f97c5c9.png)

피드백주신대로 회원가입이나 로그인등은 시스템구조도에서 상세하게 표현하지 않으면서 전체 시스템 구조도라기보다는 메인서비스(가상피팅) 시스템 구조도라는 네이밍이 적절해보입니다.
기존에 세로 flow 로 작성했는데 UI 가 명확히 보이면서도 전체 흐름을 나타내기에 공간이 부족하여 가로로 구성을 전환했습니다.
- Client 박스 내부와 Server 박스 내부에 여백이 꽤나 거슬립니다. 구성을 약간 변경하거나, 채울수 있는 아이디어가 있으면 말씀해주세요
- 여전히 human parsing 에 대한 설명은 부족합니다. 추가적으로 모델의 작동방식을 그리면 좋을 것 같습니다.

# 기능흐름도
따로 구성을 수정한것은 없고 아이콘과 확정된 UI를 반영하였습니다
### 로그인, 회원가입
![image](https://user-images.githubusercontent.com/72314987/226821601-8687a80c-e957-428e-8c83-d96511a60c44.png)

### 메인페이지
![image](https://user-images.githubusercontent.com/72314987/226822124-7668e148-0a37-4a12-9706-43a5fde217a9.png)
전체 시스템 구조도가 메인서비스 시스템 구조도로 변경되면서 메인 페이지 workflow가 다소 의미가 없어진 느낌이 들지만,
조금 더 구체적으로 작성가능해두고 필요할 때 사용하면 좋을 것 같습니다.

### User Image 수정
![image](https://user-images.githubusercontent.com/72314987/226821936-c66bafac-843f-4f58-b6e3-d062d0796f47.png)

**Comment by wynter122** [comment]
> 2. Main Page에서 Gallery Selection 이후에 Save image at local이 맞나요..? 이미지를 선택하면 중간에 모델 거쳐서 결과 페이지를 바로 보내주는 걸로 생각했는데 다시 확인해주심 좋을 것 같아요

사용자로부터 input 으로 받은 사진은 재사용하지 않으니 S3에 저장할 필요가없다고 생각해요.
모델은 이미지의 경로가 필요하기 때문에 로컬, 즉 서버 ec2의 볼륨에 사용자가 선택한 사진을 저장하고 해당 경로를 모델에 input으로 넣어준다는 의미입니다. 이건 돈혁님이 확인해주시면 될 것 같아요. 

> 3. 그 중간에 물음표는 저번에 회의에서도 상의한 내용인 것 같은데,
>    a. 플러터에서 가지고 있던 이미지 정보, 유저 정보를 보내준다
>    b. 서버에서 나머지 정보를 합쳐 모델 API에 보내준다
>    c. 모델 api에서 input 정보로 받아 사용한다
>    이렇게 세가지 과정으로 일단 생각하고 있고 맞는지 확인해주신 다음에 넣으면 될 것 같아요

이해하신 부분이 맞아요. 그걸 어떻게 압축시켜서 정확하게 표현하면 좋을지 고민중이에요!

**Comment by dh5473** [comment]
수고하셨습니다! 저도 모델 구조도 공유드릴게요!
피드백할 거 있으면 해주세요

![모델구조](https://user-images.githubusercontent.com/94889715/227250042-dbf2e766-f8bc-4fbf-82f9-14c53b8d042d.jpg)

**Comment by wynter122** [comment]
[메인서비스_시스템구조도.pdf](https://github.com/kookmin-sw/capstone-2023-08/files/11104291/_.pdf)

메인서비스 구조도 UI 변경하여 완료하였습니다.
@dh5473 확인하시고 피피티에 반영하시면 될 것 같아요.
