### ISSUE TITLE
[BE] 상품 리스트 페이지 API 개발

### ISSUE THREAD

**Issue by wynter122** [kookmin-sw/capstone-2023-08#37]
상품 리스트 페이지에서 S3에 저장된 상품 이미지를 넘겨주는 API를 개발합니다.

![image](https://user-images.githubusercontent.com/72314987/226841912-b61cbb64-593e-4d4b-9940-960fffdd6a02.png)

**Comment by grapefruit224** [comment]
flutter에도 이미지 url만 있으면 로드는 가능한 것 같거든요.
https://kibua20.tistory.com/m/235

url 리스트 반환해서 이미지 포함시키는 방법은 가능할 것 같습니다!

아 그리고 보여져야 하는 데이터 저장이 이미지, 상품 이름 만 되는 거죠? 혹시 가격은 따로 저장을 할 순 없을까요?

**Comment by dh5473** [comment]
가격.. 혹시 무신사 내에서 가격 변동이 큰 편인가요?? 적으면 괜찮은데 쿠팡처럼 변동이 심하면 관리가 어려워질 수 있을 거 같긴 해요. 가격 제공 시에는 브랜드명도 함께 제공하는 건 동의합니다.

**Comment by wynter122** [comment]
정가는 잘 변하지 않겠지만 할인가는 크지 않을까요...? 구매자입장에서 예측한거긴 합니당.
저도 가격은 제공하지 않더라고 브랜드명은 제공해도 좋을 것 같아요.
