### ISSUE TITLE
[FE] 회원 가입 페이지 구현

### ISSUE THREAD

**Issue by grapefruit224** [kookmin-sw/capstone-2023-08#39]
oauth기반 회원 가입임으로 다른 유저 정보는 받을 필요 없음.

회원 가입 전에 사용자의 사진을 먼저 받기로 하였기 때문에, oauth에서 받아온 유저 정보와 함께 사진 촬영 이나 갤러리에서 가져온 유저 정보를 함께 DB에 저장할 수 있는 페이지로 구현할 예정입니다.

**Comment by wynter122** [comment]
정정합니다. 
Django.contrib.auth 패키지만 사용중이라 Oauth 프로토콜은 아닌것같아요.

우선 확실히 필요한건 id, pw, nickname, s3에 저장된 사용자 이미지 url입니다.

**Comment by wynter122** [comment]
완료되어 이슈 닫습니다.
