### ISSUE TITLE
[중간평가] 발표자료 준비

### ISSUE THREAD

**Issue by wynter122** [kookmin-sw/capstone-2023-08#40]

**Comment by dh5473** [comment]
발표 PPT 페이지를 짜야 하는데 혹시 추가할 점이나 피드백 부탁드립니다!
모델 부분은 제가 메꿀 수 있는데, 기본 PPT 도안과 나머지 부분 도와주시면 감사하겠습니다.

1. 표지
2. 가상피팅 소개
3. 서비스 목적 소개
4. 서비스 지도화(설계도) - 플루터, 장고 등
5. 사용 모델 소개
6. 향후 지향점
7. 마무리

**Comment by wynter122** [comment]
구성은 좋은 것 같아요! 7분이 좀 남으면 1. 표지 다음에 팀원 소개를 넣어도 될 것 같아요.
제가 우선 #36 이슈를 진행중이니 4번을 주로 맡으면 될 것 같습니다.

**Comment by wynter122** [comment]
#54 에서 진행중
