### ISSUE TITLE
찜하기 기능 문제점

### ISSUE THREAD

**Issue by wynter122** [kookmin-sw/capstone-2023-08#51]
찜하기 기능을 다음과 같이 DB로 쿼리할 수 있도록 RDB를 구상중입니다.

![image](https://user-images.githubusercontent.com/72314987/226938560-a6414aa2-6390-4b25-b710-2385b7857cb5.png)

DIBS_LIST 테이블에 INSERT, DELETE 해서 찜리스트를 구성,
user id로 쿼리하여서 상품의 ranking num으로 조회하는 간단한 방법이 있습니다.

다만 저희가 현재 구상한 서비스 규칙상 치명적인 문제가 있습니다...
1. 일주일마다 상품 랭킹이 변동되기 때문에 랭킹 번호로 찜한 상품을 저장할 시 문제가 발생합니다.
이는, PK를 s3_img_url 로 지정하도록 수정한다고 가정해도
s3에 저장하는 파일명 형식 또한 {ranking_num}.jpg 등의 파일명으로 구별하기 때문에 해결이 어려울 것 같습니다.
무신사에서 제공하는 상품명이 unique 하다는 보장이 없기 때문에, PK로 지정할 다른 요소가 있을지는 마땅히 떠오르지 않는 상황입니다.

2. 1번과 같은 문제의 연장선인데, 일주일 후 데이터에서 사용자가 찜한 상품이 없을수도 있습니다.

저희가 실제로 주기적으로 크롤링을 하고 있지는 않지만, 서비스 가정상 주기적으로 신규데이터를 제공하는 어플리케이션인데 해당 문제에 대한 해결책이 마련되어야 할 것 같습니다.

@lucyya99 @dh5473 @grapefruit224

**Comment by dh5473** [comment]
1. 파일명을 {time_rankingnum}.jpg 형식으로 저장하는 건 어떤가요? 크롤링하는 시점의 시간을 저장해서 넘겨주면 될 거 같아요. unique를 부여할 때 편한 방법은 time 활용하는 게 좋을 거 같아요.
2. 가장 쉬운 방법은 이전에 크롤링 했던 데이터를 계속해서 저장하는 건데 용량이 문제될 정도일까요?

**Comment by wynter122** [comment]
1. 좋은 방법인 것 같아요. 아니면, 신규 데이터 업데이트는 짧아봤자 일주일에 한번 한다고 가정하기 때문에, 크롤링한 날짜를 경로나 파일명에 넣어도 unique 하고 데이터 식별하기도 용이할듯합니다.
2. 저도 그 방법이 가장 간단하고 현실적이라고 생각하는데, 이미지 하나에 20kb 정도고 한 번 크롤링할 때 90개 수집, 크롤링 주기가 많지 않기 때문에 용량이 문제되지는 않습니다.
다만 큰 문제점은 데이터의 무결성이 보장되지 않는다는거에요. 
1번 방법 (time 으로 파일명구성) + 데이터 삭제하지 않고 중복저장. 
이 방식을 따른다면, t 시점에서의 1위 제품과 t+1 시점의 1위제품이 실제로는 변동되지 않았지만 저희 시스템상에서는 두 데이터는 다른 데이터입니다.
만약 t 시점에서 사용자가 1위 제품을 찜 했다면 t+1 시점에서 "동일한" 제품을 찜하지 못해야하는게 정상인데 해당 방식에서 두 데이터가 같은 데이터라는것을 알 수가 없는게 문제인 것 같아요.

해결 할 수 있는 방법은 고민하면 나올 것 같은데 조금 복잡해질것같긴합니다.

위 방법에서 개선점이 있을지 우선 고민을 해보고 다른 방법도 생각해볼게요

**Comment by lucyya99** [comment]
무신사링크 확인해보니까 
https://www.musinsa.com/app/goods/3163603?loc=goods_rank
로 상품id를 그대로 표출하는 형식인것같아서 확인해보고 이 아이디를 그대로 사용하면 어떨까싶어요!

**Comment by wynter122** [comment]
상품 아이디라는게 아래 이미지에서 품번을 의미하는게 맞을까요?
<img width="686" alt="image" src="https://user-images.githubusercontent.com/72314987/227112900-9933e5b2-624b-4404-bf93-5536063bb875.png">

**Comment by lucyya99** [comment]
품번은 아닌 것 같은데 품번으로 구분이 된다면 품번으로 하셔도될 것 같아요

**Comment by grapefruit224** [comment]
예지님이 말씀하신대로

https://www.musinsa.com/app/goods/2702396 

이렇게 url 마지막이 상품 id로 설정되어있는 것 같더라고요! 저걸로 구분하면 unique한 데이터라 되지 않을까요..?

**Comment by wynter122** [comment]
아 네 확인했어요! 
근데 저 id가 사이트마다 랜덤으로 부여되는 경우도 있어서 일부러 사용하지 않았던거거든요...
인스펙트 살펴보니까 저 id로 멤버십 가격이랑 그냥 가격도 조회해서 표출하는 매커니즘인걸로 보여서 바뀌는것같지는 않아요. 
id 사용하도록 바꿔서 개발해보고 후에 id 가 변경되는지 지켜보도록 할게요

**Comment by wynter122** [comment]
id 로 유니크한 이름으로 저장되도록 크롤링 모듈 수정 완료 
#56
