### ISSUE TITLE
[중간평가] 발표 PPT

### ISSUE THREAD

**Issue by dh5473** [kookmin-sw/capstone-2023-08#54]
[캡스톤중간발표.pptx](https://github.com/kookmin-sw/capstone-2023-08/files/11053154/default.pptx)

일부 페이지 및 디테일한 부분 제외하고는 자료 완성했습니다.
3번째 페이지에 잘된 케이스 사진이 있으니 추후 깃허브 페이지 등에 활용하면 좋을 것 같습니다.
부족하면 말씀해주세요.

자료 자체에서 보완해야할 점은

1. 앱 소개 부분에 들어갈 사진 + 위치 수정
2. 팀원 소개 추가할지

정도인 것 같은데 추가로 피드백할 부분 있으면 말씀해주세요.

**Comment by wynter122** [comment]
# 추가 자료
프로젝트 진행 방법에 대해서 추가적으로 넣을 수 있다면 좋을 자료입니다!
모두 넣을 필요는 없고 한페이지정도에 간략하게 넣을 수 있으면 좋을 것 같아요.
각자 어떤 내용을 이야기하면 좋을지도 간략하게 적었습니다!

### 이슈 목록
<img width="1231" alt="이슈 목록들" src="https://user-images.githubusercontent.com/72314987/229259089-987255e1-57c0-4b86-84d2-5e402c52a95a.png">


### 이슈에서 의견 공유
<img width="842" alt="이슈에서 의견 공유" src="https://user-images.githubusercontent.com/72314987/229259085-50ed9d7d-d521-4219-b68a-16932e282f34.png">

=> 깃허브의 이슈를 사용하여 각자 어떤 일을 하고 있는지, 어떻게 진행되고 있는지 공유함.
PR을 통해 코드 리뷰 진행.
이런 방식으로 각 회의에서 어떤 내용을 이야기 해야할지 쉽게 파악할 수 있었음

### 주 2회 정기회의
<img width="1219" alt="주 2회 정기 회의" src="https://user-images.githubusercontent.com/72314987/229259091-d036bc73-bdae-4da2-9eed-6f5b4a2ee23e.png">

=> 수업시간에 진행하는 정규 회의와 별개로 매주 화요일마다 간략한 비대면 미팅을 진행함.
각자 일의 진행도나 마주하고 있는 문제점등을 공유하고 처리가 급한 사항들을 논의하여 해결


### 팀 노션을 통한 팀원끼리의 정보 공유
<img width="1219" alt="팀원끼리 정보 공유" src="https://user-images.githubusercontent.com/72314987/229259093-c555a3dc-cc82-47f2-9eae-09e49cfdd96d.png">

=> AWS 사용법 혹은 자료조사 정보를 문서화하여 공유
