### ISSUE TITLE
카메라로 사용자 모습 촬영하는 화면 개발

### ISSUE THREAD

**Issue by wynter122** [kookmin-sw/capstone-2023-08#6]
현재까지 구상된 방향에서 생각해보면
1. 메인페이지에서 "무신사 옷 입어보기" 선택 -> 카메라 촬영 화면 진입
2. 메인페이지에서 "갤러리에서 옷 선택" 선택 -> 사용자로부터 사진 받음 -> 카메라 촬영 화면 진입

두가지 상황에서 진입점이 생길 것 같습니다.
우선 카메라로 사진 촬영이 가능하게끔 구현을 하고
- 타이머
- google ml 사용 
두가지 중 가능성을 조사해서 기능을 확정하면 될 것 같아요

**Comment by wynter122** [comment]
해당 이슈에서 현재 카메라 기능이 안되는 부분을 정리해서 진행상황 공유해주시면 될 것 같아요

**Comment by lucyya99** [comment]
화면 구현이 끝났지만 추가로 개발과 정보 수집이 필요한 부분
- [ ] 카메라로 촬영한 이미지 s3에 올리기(*진행중)
- [ ] 카메라 가이드라인으로 Google Ml Kit에서 제공하는 패키지 사용이 가능한지 알아보기
- [ ] 카메라 촬영시 타이머 기능 추가
- [ ] 카메라 촬영시 셀카모드 추가
