### ISSUE TITLE
[FE] 회원가입 페이지 데이터 post 이슈

### ISSUE THREAD

**Issue by grapefruit224** [kookmin-sw/capstone-2023-08#62]
현재, 회원 가입 페이지에서는 아이디, 비밀번호, 닉네임을 입력 받고 이미지 url은 고정한 채 post되도록 하고 있습니다.

이미지 url은 @lucyya99 님이 개발 중인 카메라 화면에서 찍힌 사진으로 생성되는 것인데, 아이디/비밀번호/닉네임 과 이미지 url은 다른 페이지에서 생성되어 최종 post를 어디서 해야할지 정해야합니다.

<img width="815" alt="스크린샷 2023-03-31 오후 3 55 14" src="https://user-images.githubusercontent.com/55117023/229045850-b4a15ce8-ebfc-4a40-88d1-09b8fd46a4ea.png">

이 flow 로 "네"를 누르면 post를 할지, 순서를 바꿔 첫번째 화면을 마지막으로 설정하여 post를 할지 이 두 가지 중 어떤 방법으로 하는 것이 좋을까요?

**Comment by wynter122** [comment]
올려주신 flow 대로 네 를 누르면 전체 데이터를 post 하는게 더 나을 것 같아요
-> 이럴경우 "이 사진으로 저장할까요?" 보다는  "이 사진으로 가입을 완료할까요?" 이런식으로 바꾸는것도 좋아보여요.

다만, 이 방법을 쓰려면 데이터를 다른 페이지로 전달해야하는데 안드로이드 스튜디오에는 인텐트라는 개념이 있기는 해요.
플러터에도 비슷한게 있는 것 같긴 해서 아래 레퍼런스 참고해보시고 판단해보시면 좋겠습니다.
https://theunclesoon.blogspot.com/2020/06/flutter-route_7.html

궁금한점이 있습니다.
사용자가 아이디, 비밀번호, 닉네임 중 하나라도 빠뜨리거나 형식이 맞지 않는 폼이 있는 경우 처리가 어떻게 되나요?
-> 회원가입 데이터는 모두 not null 이라서 체크가 필요한데 체크하는 시점이 현재 어디인지 궁금합니다.

**Comment by lucyya99** [comment]
1. 저번에도 같이 고민했던 내용인것같은데 회원가입 누르고 카메라가 갑자기 나오면 저라도 당황할것같아서 카메라 전에 아이디, 비밀번호, 닉네임을 먼저 받는게 맞을것같아요!
2. 문구는 현영님 말씀하신게 더 좋은것같아서 그걸로 수정할게요
3. 페이지끼리 데이터를 받는건 navigator 메서드 안에 데이터 넣으면 전달이 가능합니다


제가 살짝 걱정이 되는건 카메라 한 화면에서 두가지를 처리하면,
1. S3에 이미지 저장 실패
2. 서버와의 통신 실패
이거 두가지를 한꺼번에 처리해야하는게 문제인것같아요
 일단은 그냥 통합해서 회원가입 실패로 만들었는데 두가지 처리를 따로 해야하는 상황이 있지 않을까요...?

**Comment by wynter122** [comment]
두가지를 따로 처리해야하는 상황이 있는지는 잘 모르겠지만 굳이 분리해보자면

s3 에 이미지를 저장하는건 프론트단에서 처리하는 일이기 때문에 
-> 성공적으로 저장되지 않았다. -> 다시 찍기 혹은 같은 사진을 다시 저장시도
로 처리해야할것같고,

2번의 경우 회원의 이미지는 s3에 저장된 상태고, s3 url 을 포함함 회원 데이터가 서버로 전달되지 않은 상황이니
s3 url 을 포함한 회원 데이터를 다시 서버로 전달
이렇게 처리하면 적절할것같아요.

**Comment by wynter122** [comment]
진행상황 공유 부탁드려요

**Comment by lucyya99** [comment]
회원가입 페이지가 없어서 일단 머지 전에 변수 만들어서 비워서 받도록 해뒀습니다. 소정님이 저번에 회원가입 API 날리는거 하신것 같으니까 일단 카메라, 마이페이지 다시 확인해서 오늘까지 PR 올려둘게요

**Comment by wynter122** [comment]
소정님이 저번주에 회원가입페이지 UI 구현하셨던것 같은데 로컬에서만 작업하신 듯 합니다.
해당부분 취합해서 Frontend 로 올려주세요!

**Comment by wynter122** [comment]
#82 가 머지되긴했는제, 위 이슈 관련되어 피드백 부탁드려요.

> 궁금한점이 있습니다.
사용자가 아이디, 비밀번호, 닉네임 중 하나라도 빠뜨리거나 형식이 맞지 않는 폼이 있는 경우 처리가 어떻게 되나요?
-> 회원가입 데이터는 모두 not null 이라서 체크가 필요한데 체크하는 시점이 현재 어디인지 궁금합니다.

> 제가 살짝 걱정이 되는건 카메라 한 화면에서 두가지를 처리하면,

S3에 이미지 저장 실패
서버와의 통신 실패
이거 두가지를 한꺼번에 처리해야하는게 문제인것같아요
일단은 그냥 통합해서 회원가입 실패로 만들었는데 두가지 처리를 따로 해야하는 상황이 있지 않을까요...?
