### ISSUE TITLE
어플의 이름과 간단한 문구, 로고 선정

### ISSUE THREAD

**Issue by lucyya99** [kookmin-sw/capstone-2023-08#7]
초기 프론트 작업을 위해 어플의 이름과 간단한 문구, 로고 선정이 필요합니다. 
## 어플 이름 후보
1. All that Fit (All of fit)
2. Fit on, Fit me
3. Virtual Fitting
4. 착붙, 딱붙, 한끗차이, ...
5. 일분쇼핑 : 일분동안 피팅해서 쇼핑 시간을 줄여준다는 의미

fit이라는 단어가 건강이나 (physical) fitness라는 뜻이 강해서 이 단어를 사용해야할지 고민입니다. 단적으로 구글 검색에 fit -> 이미지를 확인하면 전부 근육 자랑하는 사진밖에 안나옵니다. 그래서 fit이 안들어간 단어도 몇가지 찾아봤습니다. 
'옷'이 들어간 단어입니다.
- 옷매 : [옷을 차려입은 모양새나 맵시](https://opendict.korean.go.kr/wordmap/view?sense_no=503603&viewType=)
- 옷매무시 : [옷을 입을 때 매고 여미는 따위의 뒷단속](https://opendict.korean.go.kr/wordmap/view?sense_no=233417&viewType=)
- 옷맵시 : [차려입은 옷이 어울리는 모양새](https://opendict.korean.go.kr/wordmap/view?sense_no=18259&viewType=)
- 옷태 : [차려입은 옷이 어울리는 모양새](https://opendict.korean.go.kr/wordmap/view?sense_no=1385191&viewType=)
- 때때옷 : [어린아이의 말로, 알록달록하게 곱게 만든 아이의 옷을 이르는 말](https://opendict.korean.go.kr/wordmap/view?sense_no=138454&viewType=)

이걸 응용해서 아이디어를 낼수도 있을 것 같아요!

## 간단한 문구
1. Anywhere you can wear
2. 원하는 옷을 원하는 장소에서 입어보세요!

## 로고 예시
로고 작업은 [Canva](https://www.canva.com/ko_kr/create/logos/)에서 템플릿을 씌워서 작업했습니다. 다른 방법이나 더 좋은 사이트가 있다면 추천해주세요!
2번 이름 Fit on, Fit me로 작업한 로고 예시입니다.
![Fit on (2)](https://user-images.githubusercontent.com/80736490/218259275-cb15a67a-44e1-4d86-9fdf-22b69e165fe3.png)

프론트 화면도 일단은 이걸 사용해서 진행하면 될 것 같습니다!

**Comment by wynter122** [comment]
임시로 일단 하고 롱텀으로 가져가면 좋을 것 같아요.
개발하다보면 중간에 좋은 아이디어가 떠오를 것 같아요!

**Comment by wynter122** [comment]
구리지만...

1. V-fit or V-fitting (브이핏... virtual fitting...)

2. Pick and Fit (고르고 입고...)

^^........

**Comment by dh5473** [comment]
이게 착 붙는 이름이 생각이 안나네요.. 일단 던져봅니다...

1. IP: Imagine Personal styling
2. Virtual-IP (V-IP or VIP)
3. V-Fit
4. MVPs: My Virtual Personal styling
5. TMI : Try-on Me for Identity

**Comment by wynter122** [comment]
저는 돈혁님이 말씀하신것중에 4번 MVPs 좋은것같아요

**Comment by wynter122** [comment]
어플 이름 : 착붙
로고나 슬로건에 가상피팅이 드러나도록 하기!

**Comment by lucyya99** [comment]
![Screenshot_20230322_111008_Samsung Notes](https://user-images.githubusercontent.com/80736490/226784017-2691bff8-53d7-4d13-bff9-16b7e87fda53.jpg)

**Comment by lucyya99** [comment]
다들 좋은 피드백 남겨주셔서 로고가 잘 나온 것 같아요! 어플이름 & 로고 정해졌으니 여기에서 이슈 닫겠습니다

- 정사각형 버전
<img src="https://user-images.githubusercontent.com/80736490/227189535-3e7a3660-7f35-4a9d-81e6-e9be21e110dc.png" width=40%/>

- 직사각형 버전
<img src="https://user-images.githubusercontent.com/80736490/227189576-7d64c6e6-ff8a-431a-a093-9156d007b2bc.png" width=40%/>
