### ISSUE TITLE
휴대폰과 사용자가 떨어져 있어도 사진을 촬영할 수 있는 방법

### ISSUE THREAD

**Issue by lucyya99** [kookmin-sw/capstone-2023-08#8]
휴대폰을 이용해 전신 사진을 찍는 경우, 어떻게 하면 휴대폰과 사용자가 떨어져 있어도 사진을 촬영할 수 있게 만들 수 있을지에 대한 방법을 고민해봐야할 것 같습니다. 상의는 가까이에서 촬영이 가능하지만, 하의는 무조건 전신을 촬영해야 합니다.

case1) 사진으로 옷을 적용하게 만드는 경우
가이드라인에 맞게 사진을 촬영하도록 요구하고, 사용자가 사진을 촬영하도록 합니다.
case1-1) 사용자에게 핸드폰만 있는 경우.
가이드라인은 전신으로 만들어둔 상태에서 가이드라인과 맞으면 본인이 촬영버튼을 눌러야하는데, 사용자와 핸드폰이 멀리 떨어져있기때문에 버튼을 누르려면 멀리 이동해야합니다. 제가 생각한 것은 가이드라인 내에 들어오면 자동 촬영하는 것입니다.
참고 어플인 ROUNDS에서는 가이드라인에 맞으면 바로 사진 촬영을 시작하고, 3초 동안 얼굴을 좌우로 천천히 돌리면서 사진을 촬영합니다. 그리고 그 중에서 베스트 컷을 골라 화면에 띄워주고, 사용자에게 '이 사진으로 피팅을 시작합니까?'를 선택하게 합니다.
저희도 이 방식처럼 가이드라인에 들어오면 자동으로 촬영하도록 하면, 전신 거울이 없더라도 촬영이 가능합니다.
case1-2) 사용자에게 전신거울이 있는 경우.
전신거울이 존재하면 손에 핸드폰을 든 상태로 본인이 촬영이 가능합니다.
case2) 만약 실시간으로 옷을 적용하게 만드는 경우, 전신 거울이 앞에 있는 경우가 아니면 확인이 불가능합니다. 그래서 만약 카메라 화면에서 옷을 실시간으로 적용하도록 만든다면, 전신 거울이 앞에 있다는 가정을 하거나, 전신 거울 앞으로 이동해달라는 경고 문구가 있어야할 것 같습니다.

자동 촬영은 카메라 자체가 화면을 캡처해서 가지고 있는 거라서 사용자가 가이드라인에 맞게 들어왔는지 확인하는 방법만 고민하면 될 것 같습니다!
이 방법에 따라 UI나 어플 사용 흐름이 바뀔 수 있기 때문에 이슈로 작성하는 것이 맞다고 생각했습니다. 생각나는 다른 방법이나 다른 케이스가 있다면 알려주세요!

추가적으로 노션에도 참고자료로 올려두었는데, 다른 어플들의 사진 촬영 방법입니다.

다른 어플의 사진 촬영 방식
뒷배경이 하얀곳 / 조명이 밝은 곳 / 카메라 위치가 배꼽~골반 / 앞모습, 옆모습을 촬영한다 (Zeekit, VR my Fiit)
1번 조건이 갖춰진 공간을 만들어 촬영한다 (Q FIT)
TV 화면에 미러링한 후 사용자가 핸드폰의 각도를 조절해 촬영한다 (KT AR 쇼룸)
사진 촬영을 하지 않고, 사용자에게 키/몸무게/평소입던사이즈 등을 입력받아 정해진 4~5가지 Body Shape을 가진 모델의 아바타를 가져와서 피팅한다 (Covernat, Style.me)
전신촬영이 필요없는 작은 소품들을 피팅한다
이런 5가지 사례가 있었습니다. 4~5번은 전신 촬영이 필요없어 저희가 참고할만한 부분은 아니지만, 다른 어플의 솔루션이기에 일단 적어보았습니다.
생각보다 '사진 촬영' 자체의 솔루션을 고민하는게 어렵더라구요. 이것도 함께 생각해보았으면 합니다.

**Comment by lucyya99** [comment]
[wynter122](https://github.com/wynter122) commented [3 weeks ago](https://github.com/wynter122/Capstone-Project-2023-1/issues/7#issuecomment-1407627256) • 
정리해주신것들 잘 읽어보았습니다.

우선 "전신 촬영을 어떻게 해야하는가?"에 대한 문제에 대해, 말씀하신 방법 중

사용자로부터 사진을 input으로 받는다.
가이드 라인에 맞추면 자동으로 인식되어서 사진을 찍을 수 있도록 한다.
이 두가지가 가장 괜찮을 것 같습니다.
둘 중에서도 가장 괜찮은것은 두번째 방법으로 밀고 가는것이 좋을 듯 해요
-> 첫번째 방법을 사용할 경우, 해당 사진으로 모델이 정상적인 결과를 뱉을 수 있는지 확인을 하는 작업이 필요하기 때문에 두번의 일을 해야됨.
-> 두번째 방법만 사용하는것이 좋아보임. 즉 어플에서 전신 사진 촬영이 필수.
이 부분에 있어서는 타이머를 사용하는게 가장 현실성이 있을 것 같아요.
물론 가이드 라인에 맞추어져 있을 때 어플에서 촬영을 한다면 좋겠지만, 프론트단에서 그게 적용 가능할지는 조사가 필요해 보입니다.
자세하게 조사해보지는 않았지만, 제 생각에는 프론트단에서 비전 기술을 사용해야하지 않나 싶어요.
플러터에서 사용할만한 패키지로는 https://developers.google.com/ml-kit?hl=ko 가 있는 것 같습니다.
만약 해당 접근법이 맞다면, 프론트단에서 작업, @dh5473 가 도와주시면 될것 같아요.

그 방법 말고는 5초~ 7초정도의 타이머를 사용 + 가이드라인 틀만 카메라 화면에 제공하는 것도 간단하게 적용할 수 있는 방법 같아요.

문제점
처음에 말한 AR 처럼 움직이는 피사체에 대한 피팅 서비스는 저희가 사용하려는 모델로 적용가능한지 잘 모르겠어요.
또한, 말씀하신 문제점들 중 "전신 사진은 사용자가 핸드폰으로 사용 시 멀리서 확인이 불가능하다" 라는 문제점을 정확히 짚어주셨습니다.
생각해보면 이 부분은 동적 피사체에 대한 실시간 피팅을 제공할 경우에만 문제가 되는 것 같아요.
단순히 정적인 사진에 대한 결과를 제공해준다면 문제는 해결될것으로 보입니다.

정적 이미지를 받아서 결과를 제공한다
모니터나 노트북에 미러링하여 동적인 피팅 결과를 보여준다
두가지 방법으로 해결 가능할 것 같은데, 저는 초기 단계에서는 1번 방향으로 가는것이 좋을 것 같다고 생각해요.
사용자에게 [키, 몸무게, 사이즈] 등을 입력받아 피팅한다.
이 문제는 @dh5473 가 제시한 모델에 적용이 가능한지 확인 부탁드립니다.
제가 알기로는 그런 정보가 필요 없을 것 같고, 모델에도 적용이 불가능하다고 알고있어서 추가적인 요소로도 사용이 어려울 것 같다고 생각합니다.

정리
사진 자동 촬영에 대해서는, 타이머 활용, 가이드 라인 활용이 있음.
둘 중 더 편하게 사용 가능한것은 타이머 + 이미지 뿐인 가이드라인 이라는 생각이 들며, 가이드라인에 맞춘 자동 촬영 기법은 프론트 단에서 적용 가능한지 조사해봐야함.
동적 피사체에 대한 피팅 보다는, 정적 이미지에 대한 피팅 결과를 제공하는것이 현재로서는 좋아보임.
사용자의 메타데이터를 입력받는것은 모델 특성상 의미 없는것으로 파악됨. @dh5473 확인 부탁드려요.
@dh5473
Collaborator
[dh5473](https://github.com/dh5473) commented [3 weeks ago](https://github.com/wynter122/Capstone-Project-2023-1/issues/7#issuecomment-1408583815)
구현 자체는 앱 내 사진 촬영보다 사용자가 사진을 input하는 게 훨씬 쉬울 거라 생각이 듭니다. 물론 타이머를 이용한 사진 촬영도 구현이 가능해보여서 어느 방향으로 가도 상관 없을 듯합니다. 앱 퀄리티를 생각하면 말씀하신 앱 내 직접 촬영, 타이머가 좋아보여요.
프론트 단에서 비전 기술을 사용한다는 말이 어떤 의미인지 모르겠습니다. 또한 말씀해주신 사이트에서 저희 프로젝트에 맞는 태스크를 확인해봤는데 자바와 코틀린 위주로 제공하고 있어서, 플러터에서 참고하기는 어려워 보입니다.
가이드라인 내에 들어오면 촬영을 시작하는 것은 어려워 보입니다. 개발을 하기 위해서는 어떤 방식으로 구현하겠다 라는 그림이 그려져야하는데 저는 잘 그려지지 않네요. 의견 있으시면 공유해주세요.
미러링 역시 3번과 마찬가지입니다. 백에서는 어떤 방식으로 API를 구현할지, 프론트에서는 어떻게 받아올지.. 어느 정도 흐름이 그려져야 합니다. 안그려진다면 참고자료라도 많아야해요.
아바타는..저희 주제의 취지에 벗어날 뿐만 아니라 구현도 어려울 거 같습니다. 또한 사용자 입장에서 몸무게와 같은 민감한 정보들을 입력해야 한다는 점 역시 거부감이 들 수 있을 거라고 생각합니다. 현영님 의견대로 저희 프로젝트와 모델 특성상 의미가 없을 것 같아요.
@wynter122
Owner
[wynter122](https://github.com/wynter122) commented [3 weeks ago](https://github.com/wynter122/Capstone-Project-2023-1/issues/7#issuecomment-1409913394) • 
프론트단에서 비전기술을 사용한다는것은, 말 그대로 가이드라인내에 들어오면 촬영을 시작하기 위해서 비전기술을 사용한다는 것입니다.
Google ML에서 제공하는 패키지중에 사용할 수 있을법한 것이 있는것을 공유드린것이고, 실제 적용 가능한지는 조사 및 테스트가 필요해보여요.
플러터에서 사용할 수 있는 패키지또한 제공 하고 있습니다. 레퍼런스 관련해서는 문제가 없어보여요 https://pub.dev/documentation/google_ml_vision/latest/google_ml_vision/google_ml_vision-library.html

해당 기능을 구현하기 위해서는 프론트단에서 작업이 필요해보여요.
앱 퀄리티 및 개발 난이도를 생각했을때 간단하게 타이머로 구현하는것이 좋아보이고,
가이드라인 내에 맞춰지면 자동촬영 을 구현하고자 한다면, 돈혁님 말씀대로 구현할 수 있는 "가능성"을 조사하는것이 우선인 듯 합니다.
프론트 작업인만큼 @lucyya99 가 알려드린 참고자료를 살펴보고, 그 외에도 플러터에서 구현 가능한 적절한 패키지가 있는지 조사해보면 될 것 같아요.

+ 사용자로부터 전신사진을 input으로 받는것은 괜찮은 방법이지만 태스크가 너무 간단하기도 해서 차선책 정도로 생각해두면 좋을 것 같아요.

**Comment by wynter122** [comment]
#6 에서 진행중인 이슈
