### ISSUE TITLE
[FE] 사용자로부터 옷 이미지를 받아서 s3에 저장하기

### ISSUE THREAD

**Issue by wynter122** [kookmin-sw/capstone-2023-08#80]
### 목표
아래 UI 에서 "갤러리에서 고르기" 를 선택했을 경우 백 단에서 처리할 api 가 필요합니다.
<img width="344" alt="image" src="https://user-images.githubusercontent.com/72314987/230094894-918e7a88-a61d-4ec1-9ce1-e9304e984a20.png">

현재 문제되는 부분은 **옷 이미지 사진을 어디에 저장해 둘 것인지** 입니다.
모델에 돌린 result 이미지를 서버에 저장해두고 제공하지 않기로 결정되었습니다.
따라서, 사용자가 제출한 옷 사진은 모델을 돌릴때에만 필요하기 때문에 굳이 s3에 저장하지 않아도 됩니다. 
그렇다면 옷 이미지를 로컬, 즉 서버가 돌아가는 인스턴스의 볼륨에 저장한 뒤 해당 이미지를 사용 후 폐기처분 하는것이 효율적인 방법일것입니다.

하지만, 현재 서버가 구동될 방식이 세가지로 나뉩니다.
1. 서비스 서버와 모델 서버를 함께 둔다 -> 추후 현재 데모 서버의 인스턴스 유형 변경 필요
2. 서비스 서버와 모델 서버를 따로 둔다 -> 서비스 서버는 t2.micro, 모델 서버는 gpu 서버
3. 서비스 서버는 ec2 인스턴스, 모델은 따로 gpu 빌려서 (ec2 에서 안돌아갈 경우 차선책)

1번의 경우, 로컬에 저장하는 방법을 그대로 사용하면 됩니다. 다만, 2,3번의 경우 로컬에 저장하면 모델에서 해당 이미지를 찾을 수 없습니다.
따라서, 2, 3번으로 서버가 구동될 때는 s3에 저장 할 수 밖에 없습니다.
s3 에 저장할 경우에는 파일명을 {user_id_time}.jpg 와 같이 유니크하게 설정하면 될 듯 합니다.

아직 g4dn 인스턴스에서 모델이 정상적으로 동작할지 테스트해보지 않아서 어떤 방향으로 구현할지는 정할 수 없는것같습니다.
이번 주말에 @dh5473 께서 테스트 하실 예정이니 결과를 공유해주시면 그에 맞게 방향을 결정하면 될 것 같습니다.

**Comment by dh5473** [comment]
g4dn 인스턴스에서 간단하게 모델 테스트해보았고, 정상적으로 동작합니다! 해당 이슈는 곧 올리겠습니다.

**Comment by wynter122** [comment]
중간평가 피드백에서 나온 "사용자로부터의 결과이미지 피드백 받기" 솔루션을 위해 결과이미지를 s3에 저장하는것으로 결정되었습니다.

**Comment by wynter122** [comment]
서비스 서버 & 로컬 서버를 같은 인스턴스에 배치하도록 결정되었습니다.
따라서 사용자로부터 받은 옷 이미지는 로컬에 임시 저장하면 되겠습니다.

**Comment by dh5473** [comment]
@lucyya99 

이전 이슈에 사진 이름을 time-~ 라고 저장하셨다고 했는데 아래처럼 바꿔주시면 감사하겠습니다!
옷 사진 -> {self.uid}_cloth.png
사람 사진 -> {self.uid}_human.png

사용자로부터 받는 옷 이미지는 인스턴스 서버에 저장해주시고,
아래와 같이 json 형식으로 request 보내주시면 될 거 같아요.

data['user_id']
data['cloth_img_path']
data['preprocessing_cloth_img_path']
data['result_img_path']


사람 이미지의 경우 다음과 같은 형식입니다.
data['user_id']
data['human_img_path']
data['preprocessing_human_img_path']
data['human_parsing_keypoints_path']

**Comment by wynter122** [comment]
피팅 결과의 피드백을 받는 파이프라인을 구상하는 단계에서
갤러리에서 고르기를 통해 받은 사진은 s3 버킷에 저장하도록 계획이 변경되었습니다.

**Comment by wynter122** [comment]
@lucyya99 

### 갤러리로부터 옷 사진 골라서 s3에 저장하기

api gateway 는 똑같이 s3 에 put 하는거라서 따로 또 만들지 않았고,
bucket name 이랑 file name 만 신경써서 업로드 하시면 됩니다.

- bucket name :  user-cloth-img
- file name : uid_cloth.png

이렇게 해주시면 되겠습니다!

**Comment by lucyya99** [comment]
@wynter122 
presigned url로 성공해서 이걸 사용하는게 좋을것같은데, 저번에 참고자료 주신걸 다시보니 버킷이랑 key 부분은 서버에서 처리해야되는것같아요

```python
url = boto3.client('s3').generate_presigned_url(
    ClientMethod='get_object', 
    Params={'Bucket': 'flutter-filepicker-test', 'Key': 'test.md'},
    ExpiresIn=3600
)
```

다시 확인해주세요! 확인되면 바로 수정 들어갈게요

- 돈혁님이 말씀하신 부분은 결과 보내주는 api 완료되면 [결과화면 + 갤러리 선택화면] 수정하면서 같이 수정하겠습니다!

**Comment by dh5473** [comment]
@lucyya99 
저 위에 댓글은 예전 거고 지금은 user_id + human s3경로 혹은 cloth s3경로 담아서 request 보내시면 돼요!
![image](https://user-images.githubusercontent.com/94889715/235196050-7d520e2b-6a46-4e9d-a00b-c65d3132c501.png)

**Comment by dh5473** [comment]
그리고 이미지들은 다 만약 user_id가 12345라면

12345_cloth.png
12345_human.png

이런 식으로 저장할 거에여

**Comment by wynter122** [comment]
아... 한시간전에 성공하셨군요...! 지금 확인했어요
그러면 presinged url 받을때 같은 api를 사용해야하니 버킷명이랑 파일이름을 클라로부터 input 으로 받아서 처리하는게 좋겠어용

**Comment by lucyya99** [comment]
테스트 완료해서 이슈 닫습니다..!
