### ISSUE TITLE
[중간평가] 발표 녹화

### ISSUE THREAD

**Issue by dh5473** [kookmin-sw/capstone-2023-08#83]
https://www.youtube.com/watch?v=6nCfT2ovA6s

최종 발표 영상을 녹화해서 위 링크에 올려두었습니다.

피드백 부탁드려요.

**Comment by wynter122** [comment]
참고로 노션 참고자료 > 중간발표 예상질문 및 답변 페이지 만들어두었는데
혹시 괜찮다면 예상 Q&A 해당 페이지에 같이 작성할까요..?

**Comment by dh5473** [comment]
녹음이라서 최대한 또박또박 말하는 것과 자연스럽게 말하는 것 사이를 찾았는데..쉽지 않네요

**Comment by wynter122** [comment]
녹음인만큼 어쩔수없는것같아요 그부분은 ㅎㅎ 고생하셨어요 준비 잘 해주셔서 감사합니다!

**Comment by lucyya99** [comment]
발표영상 확인을 이제야 했네요.. 😥 저도 저번 학기에 처음으로 녹화 영상 촬영해봤는데 자연스럽게 말하는게 정말 쉽지 않아요! 분량도 딱 맞고 이정도면 괜찮을것같아요 고생하셨습니다!!

@wynter122 
어제 허대영 교수님 자료 보면서 예상 질문 조금씩 작성해뒀는데,
1. 무신사에서 크롤링해오는 것에 대한 저작권 문제
2. 인공지능 모델의 성능이 안나왔을 경우? 앱상에서의 처리? (부작용 관련 질문)
3. 착붙에서 왜 000 기술을 적용하나요?

등등은 조금 더 고민이 필요한 것 같아요..ㅠ

**Comment by wynter122** [comment]
발표 성공~
