### ISSUE TITLE
[FE] 사용자의 로그인 정보 유지

### ISSUE THREAD

**Issue by wynter122** [kookmin-sw/capstone-2023-08#89]
다음 상황에서 사용자의 로그인 정보가 필요합니다.

1. 마이페이지 : 백으로 api 보내지 않고 바로 닉네임 보여주기
2. 회원정보수정 : presigned_url 반환을 위해 사용자 id 가 필요함 (s3 파일의 키 값이 사용자 id)
3. 찜목록 : 사용자 id 를 input 으로 api 로부터 사용자별 찜 리스트 반환받음
4. 옷 리스트 페이지 : goods 리스트 외에 따로 사용자 id 로 찜한 목록 반환받아서 찜 버튼 on 처리 필요
5. 사용자로부터 옷 이미지 받기 : 사용자 id 정보로 옷 이미지를 저장해야합니다.
6. 모델로 요청하기 : 사용자 id 필요

따라서, 사용자의 id 와 nickname 정보는 필수적으로 유지해야합니다.
이를 가능하게 할 방법을 조사하고 기술한 로직을 구현합니다.

**Comment by lucyya99** [comment]
## Token 구성
HEADER, DATA, PAYLOAD
DATA 부분에 encoding된 사용자 정보를 보내주면, 프론트에서 flutterSecureStorage에 저장
따라서, 플러터에서는 flutterSecureStorage라는 곳에 토큰을 저장해두고 필요할 때마다 decoding해서 사용하기만 하면 됨
Access Token은 사용자가 검증된 사용자인지 확인하기 위해 필요한 것이므로 header에 보낼 때마다 넣어서 같이 전송

## Refresh Token 보낼 때
1. 기본적으로는 Access Token이 만료되었을 때, Refresh Token이 만료되었을 때
2. 회원정보 수정, 로그아웃
3. 찜목록 수정

## Todo
로그인할 때 Header에 Access Token, Refresh Token 보내도록 설정

## 프론트단에서 로그인을 확인하는 부분
Splash Screen에서 확인하고, 나머지 화면 전부 세팅하도록 설정하도록 했는데, 생각해보니
- 만약 로그인이 되었는데, 중간에 토큰이 만료되는 경우?
- 중간에 로그인이 된 경우?

Splash Screen은 앱이 켜지고 처음에만 나타나는 화면이기 때문에,
이 부분은 이 두가지 경우에 대한 처리를 어떻게 하는지 조금 더 조사해보고 처리하는 게 좋을 것 같아요

## Token에 넣을 정보
user-id, user-pw 넣어서 보내는 것은 확실한데,
나머지 정보인 user-name, user-img-url는 같이 보낼 수 있는지, 그걸 프론트에서 저장하고 있어야하는지까지는 아직 잘 모르겠어서 조금 더 공부해보고 알려드릴게요

**Comment by wynter122** [comment]
#95 #98 에서 테스트 완료되어 해당 이슈는 close 합니다.
