### ISSUE TITLE
[DL] 타겟 데이터 카테고리의 적절성 판단

### ISSUE THREAD

**Issue by wynter122** [kookmin-sw/capstone-2023-08#9]
본 이슈는 #2 이슈에서 결정된 카테고리별로 모델의 결과가 적절한지 판단하는 이슈입니다.
간단하게 테스트해보고 결과를 정리해서 공유해주시면 될 것 같습니다.

**Comment by dh5473** [comment]
진행해보았는데, 당장 가지고 있는 모델로는 상의만 정확하게 나옵니다. input이미지가 하의로 주어져도 상의에 입히네요.. 가능하다면 코드를 수정해보거나 상하의 파트를 나눠서 진행하는 등의 다른 방안을 찾아보아야할 것 같네요. 우선은 로컬에서 모델을 돌리는 것을 최우선으로 하고 이후에 코드를 수정해보겠습니다.

**Comment by wynter122** [comment]
확인 감사드려요. 그러면 우선 상의를 입히는걸로 하고, 말씀하신대로 코드 수정을 통해서 하의나 아우터도 가능하도록 수정하면 좋을 듯 합니다!

**Comment by wynter122** [comment]
우선 현재는 상의로만 진행하는것으로 확인되었고, 추가적인 코드 수정 및 개선점 연구는 다른 이슈에서 진행하므로 close 합니다
