### ISSUE TITLE
[BE] 결과 사진 피드백

### ISSUE THREAD

**Issue by dh5473** [kookmin-sw/capstone-2023-08#99]
### 피드백 구조 설계

사진 결과가 나온 후 유저 피드백 파이프라인을 구축하려고 합니다.
사진 결과 저장 화면과 비슷하게 좋아요 싫어요 정도로 구성해주시면 될 거 같아요.

백엔드에서는 상세 함수는 utils.py에 구현하고,
함수 기능은 결과에 사용한
옷과 사용자 이미지를 s3에 저장하는 것으로 하겠습니다.
(추후 학습에 사용될 이미지로)

프론트에서는 request로 uid, 옷과 사람 이미지 경로를 보내주시면 됩니다.

![image](https://user-images.githubusercontent.com/94889715/234269391-ecfacabb-fc46-464d-b822-e0d1f30b576a.png)

**Comment by wynter122** [comment]
#143  완료되어 이슈 닫습니다
